### ISSUE TITLE
Clicking and dragging the control points doesn't seem to work.

### ISSUE THREAD

**Issue by SirNate0** [jdherman/colormap#1]
The knots swell, and my pointer changes to a little hand thing, but dragging doesn't change anything.

**Comment by jdherman** [comment]
What browser / OS? 

I haven't kept this up to date over the years, so it's possible a browser update changed how they do event handling. It still works for me on OSX/Chrome.

**Comment by SirNate0** [comment]
Chrome 59 on Ubuntu 16.04. It works with Firefox, though.

**Comment by jdherman** [comment]
Alright, I appreciate the bug report but I'm not sure there's much I can do about it right now. I haven't been doing cross-browser testing, and the site is a few years old now so some javascript things may have changed since then.

I'll leave this issue open in case anyone else confirms the same problem. In the meantime if you'd like to see it fixed, go digging in Chrome's developer console and see if you can catch what errors are happening (if any). The drag event is defined here:
https://github.com/jdherman/colormap/blob/master/public/javascripts/colormapLine.js#L39

**Comment by bonanza123** [comment]
I guess I have a similar issue with firefox, the console says:
```
Blocked loading mixed active content “http://fonts.googleapis.com/css?family=Raleway:400,200”[Learn More] colormap
Blocked loading mixed active content “http://code.jquery.com/jquery.js”[Learn More] colormap
Blocked loading mixed active content “http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js”[Learn More] colormap
Blocked loading mixed active content “http://fonts.googleapis.com/css?family=Raleway:400,200”[Learn More] colormap
Blocked loading mixed active content “http://code.jquery.com/jquery.js”[Learn More] colormap
Loading failed for the <script> with source “http://code.jquery.com/jquery.js”. colormap:419:1
ReferenceError: jQuery is not defined[Learn More] bootstrap.min.js:6:4
Blocked loading mixed active content “http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js”[Learn More]
```

I guess that can be easily fixed by load these files via HTTPS instead of HTTP.

**Comment by jdherman** [comment]
Hi @bonanza123 thanks for the info. I just removed the http protocol following this post
https://stackoverflow.com/questions/18251128/why-am-i-suddenly-getting-a-blocked-loading-mixed-active-content-issue-in-fire

... see if it works now? For me it's working in chrome and firefox on OSX.

**Comment by bonanza123** [comment]
@jdherman perfect, thanks so much!
